app:
  name: "sample-app4"
  version: "1.0.4" #updated the version
  environment: "dev3"

database:
  host: "db-dev.example.com"
  port: 5432
  username: "devuser1"
  password: "devpassword1"

logging:
  level: "DEBUG"
  format: "json"

feature_flags:
  enable_new_ui: false
  enable_beta_features: false
