app:
  name: "sample-app"
  version: "1.0.2" #updated the version
  environment: "dev2"

database:
  host: "db-dev.example.com"
  port: 3789
  username: "devuser"
  password: "devpassword"

logging:
  level: "DEBUG"
  format: "json"

feature_flags:
  enable_new_ui: true
  enable_beta_features: false
