app:
  name: "sample-app"
  version: "1.0.3" #updated the version
  environment: "development"

database:
  host: "db-dev.example.com"
  port: 5432
  username: "devuser"
  password: "devpassword"

logging:
  level: "DEBUG"
  format: "json"

feature_flags:
  enable_new_ui: true
  enable_beta_features: false
