replicaCount: 2

image:
  repository: "my-docker-repo/sample-app"
  tag: "latest"

service:
  type: "ClusterIP"
  port: 9090

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

env:
  - name: "APP_ENV"
    value: "development"
  - name: "LOG_LEVEL"
    value: "debug"
